### ISSUE TITLE
Standardize did:web

### ISSUE THREAD

**Issue by msporny** [w3c/did-wg-charter#16]
This issue has been raised for discussion by the DID WG based on feedback in Google's Formal Objection to DID Core 1.0:

https://lists.w3.org/Archives/Public/public-did-wg/2021Oct/0022.html

Google has suggested that while `did:web` does not meet their "truly decentralized" requirement for a DID Method, that they suggest that the DID WG standardizes it.

Should a future DID WG Charter standardize `did:web`?

**Comment by brentzundel** [comment]
Beginning standardization of DID Methods was added to the charter in #20 
One of these may be `did:web`
