### ISSUE TITLE
need github.io render of draft charter

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-wg-charter#21]
@pchampin would it be possible to set up a github.io preview of the draft DID WG charter, similar to https://w3c.github.io/vc-wg-charter/ ?

**Comment by pchampin** [comment]
This is already configured... and the link is provided in the README :)

**Comment by TallTed** [comment]
Because it makes life easier... the [link is here](https://w3c.github.io/did-wg-charter/), now, too.
