### ISSUE TITLE
Standardize did:jwk instead of did:key

### ISSUE THREAD

**Issue by OR13** [w3c/did-wg-charter#23]
See https://github.com/w3c/did-wg-charter/issues/15

did:jwk addresses certificates and standard key representations (JWK) better than did:key does.

**Comment by peacekeeper** [comment]
I think the did:key vs. did:jwk discussion also has to do with what public key representations will become common in DID documents in the future (publicKeyJwk vs. publicKeyMultibase).

**Comment by OR13** [comment]
yes, and it comes down to what is MTI... 

- which did methods are MTI? 
- which verification method material formats are MTI?

Addressing these, would help address concerns that we have not protected implementers from optionality... and that we have therefor not solved for interoperability sufficiently.

**Comment by brentzundel** [comment]
Beginning standardization of DID Methods was added to the charter in #20 
One of these may be `did:jwk`
